name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install Packages
      run: npm install
    - name: Lint Files
      run: node Makefile lint
    - name: Check Rule Files
      run: node Makefile checkRuleFiles
    - name: Check Licenses
      run: node Makefile checkLicenses

  test_on_node:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15.x, 14.x, 13.x, 12.x, 10.x, "10.12.0"]
        include:
        - os: windows-latest
          node: "12.x"
        - os: macOS-latest
          node: "12.x"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Cache node modules
        id: cache
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Packages
      run: npm install
      if: ${{ !startswith(matrix.node, '15') }} || steps.cache.outputs.cache-hit != 'true'
    - name: Install Packages
      run: npm install --legacy-peer-deps
      if: ${{ startswith(matrix.node, '15') }}
    - name: Test
      run: node Makefile mocha
    - name: Fuzz Test
      run: node Makefile fuzz

  test_on_browser:
    name: Browser Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Cache node modules
        id: cache
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Packages
      run: npm install
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Test
      run: node Makefile karma
    - name: Fuzz Test
      run: node Makefile fuzz
